version: '3'
services:
  diffusers-lab:
    container_name: my-diffusers-lab
    image: diffusers-lab
    stdin_open: true
    tty: true
    command: /bin/bash
    ports:
      - "6006:6006" 
    networks:
      default:
        aliases:
          - tensorboard
    working_dir: /app
    volumes:
      - ./:/app
    deploy:
      restart_policy:
        condition: none
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    build:
      context: .
      dockerfile: Dockerfile
